{
 "title": "Docker Containers",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(container_tasks_state,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", job=~\".*$host\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\", job=~\"$host\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{job=~\".*$host\"}"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$host\"}) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes{job=~\"$host\"} + node_memory_Cached_bytes{job=~\"$host\"}) ) / sum(node_memory_MemTotal_bytes{job=~\"$host\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", job=~\".*$host\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", job=~\"$host\"} - node_filesystem_free_bytes{mountpoint=\"/\", job=~\"$host\"}) / node_filesystem_size_bytes{mountpoint=\"/\", job=~\"$host\"}  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{job=~\".*$host\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\", job=~\".*$host\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"$host\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=~\"$host\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=~\"$host\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{job=~\"$host\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\", job=~\".*$host\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", job=~\"$host\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\", job=~\".*$host\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\", job=~\".*$host\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", job=~\".*$host\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", job=~\".*$host\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}