{
 "title": "Hosts",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(node_boot_time_seconds, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=~\"$host\"} - node_boot_time_seconds{job=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\", job=~\"$host\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", job=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{job=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\", job=~\"$host\"})"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "host" },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"$host\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running{job=~\"$host\"}",
     "legendFormat": "running"
    },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_intr_total{job=~\"$host\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  { "title": "Network Usage $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "host" },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", job=~\"$host\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", job=~\"$host\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  { "title": "CPU Usage $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "host" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=~\"$host\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", job=~\"$host\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  { "title": "Memory Usage $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "host" },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$host\"} - (node_memory_MemFree_bytes{job=~\"$host\"} + node_memory_Buffers_bytes{job=~\"$host\"} + node_memory_Cached_bytes{job=~\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  { "title": "IO Usage $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "host" },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=~\"$host\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{job=~\"$host\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  { "title": "Swap Usage $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "host" },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=~\"$host\"} - node_memory_SwapFree_bytes{job=~\"$host\"}",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{job=~\"$host\"}[1m]) * 4096 or irate(node_vmstat_pswpin{job=~\"$host\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{job=~\"$host\"}[1m]) * 4096 or irate(node_vmstat_pswpout{job=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}