global:
  scrape_interval: 30s
  evaluation_interval: 30s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "docker-host-alpha"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "172.17.100.203"
    scrape_interval: 15s
    static_configs:
      - targets: ["monitoring_nodeexporter:9100"]

  - job_name: "172.17.100.202"
    scrape_interval: 15s
    static_configs:
      - targets: ["172.17.100.202:9100"]

  - job_name: "cadvisor@172.17.100.203"
    scrape_interval: 15s
    static_configs:
      - targets: ["monitoring_cadvisor:8080"]

  - job_name: "prometheus@172.17.100.203"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway@172.17.100.203"
    scrape_interval: 30s
    honor_labels: true
    static_configs:
      - targets: ["monitoring_pushgateway:9091"]

  - job_name: "blackbox@172.17.100.203"
    scrape_interval: 30s
    metrics_path:
      /probe
      #    static_configs:
      #- targets:
      #    - https://server01.heartlakefriendshipzone.com/matchmake/lego-friends
      #    - https://server02.heartlakefriendshipzone.com/matchmake/lego-friends
      #    - https://server06.heartlakefriendshipzone.com/matchmake/lego-friends
      #    - https://server07.heartlakefriendshipzone.com/matchmake/lego-friends
      #    - https://server11.heartlakefriendshipzone.com/matchmake/lego-friends
      #    - https://server12.heartlakefriendshipzone.com/matchmake/lego-friends
      #    - https://server01.app.funables.com
      #    - https://server02.app.funables.com
      #    - https://server06.app.funables.com
      #    - https://server07.app.funables.com
      #    - https://server10.app.funables.com
    file_sd_configs:
      - files:
          - /etc/prometheus/blackbox_targets.yml
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "monitoring_alertmanager:9093"
#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']

